name = "irismath"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["IrisMath"]

[leanOptions]
pp.unicode.fun = true 
relaxedAutoImplicit = true
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[require]]
name = "iris"
path = "../IrisLean/"

[[lean_lib]]
name = "IrisMath"
