name = "iris"
defaultTargets = ["Iris"]
testDriver = "IrisTest"
lintDriver = "batteries/runLinter"

[[require]]
name = "Qq"
scope = "leanprover-community"
rev = "v4.32.0"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.32.0"

[[lean_lib]]
name = "Iris"

[[lean_lib]]
name = "IrisTest"
globs = ["IrisTest.+"]

[[lean_exe]]
name = "dumpPortingData"
srcDir = "../scripts"
root = "DumpPortingData"
supportInterpreter = true

[[lean_exe]]
name = "check-imports"
srcDir = "../scripts"
root = "CheckImports"

[leanOptions]
linter.missingDocs = false
linter.extra.unreachableTactic = true
linter.redundantVisibility = true
linter.extra.unnecessarySeqFocus = true
weak.linter.iris.style.setOption = false
weak.linter.iris.style.missingEnd = true
weak.linter.iris.style.cdot = true
weak.linter.iris.style.dollarSyntax = true
weak.linter.iris.style.lambdaSyntax = false
weak.linter.iris.style.longLine = false
weak.linter.iris.style.nameCheck = false
weak.linter.iris.style.openClassical = true
weak.linter.iris.style.show = true
weak.linter.iris.dupNamespace = true
