name = "iris"
defaultTargets = ["Iris"]
testDriver = "IrisTest"

[leanOptions]
linter.ambiguousOpen = false

[[require]]
name = "Qq"
scope = "leanprover-community"
rev = "v4.33.0-rc1"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.33.0-rc1"

[[lean_lib]]
name = "Iris"

[[lean_lib]]
name = "IrisTest"
globs = ["IrisTest.+"]

[[lean_exe]]
name = "dumpPortingData"
srcDir = "../scripts"
root = "DumpPortingData"
supportInterpreter = true

[[lean_exe]]
name = "check-imports"
srcDir = "../scripts"
root = "CheckImports"
