name = "iris"
defaultTargets = ["Iris", "IrisProofMode"]
testDriver = "IrisTest"

[[require]]
name = "Qq"
scope = "leanprover-community"
rev = "v4.32.0"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.32.0"

[[lean_lib]]
name = "IrisProofMode"
roots = ["Iris.ProofMode"]
globs = ["Iris.ProofMode", "Iris.ProofMode.+"]
precompileModules = true

[[lean_lib]]
name = "Iris"
globs = ["Iris", "Iris.Algebra.+", "Iris.BI.+", "Iris.Examples.+",
         "Iris.HeapLang.+", "Iris.Init", "Iris.Instances.+",
         "Iris.ProgramLogic.+", "Iris.Std.+"]

[[lean_lib]]
name = "IrisTest"
globs = ["IrisTest.+"]

[[lean_exe]]
name = "dumpPortingData"
srcDir = "../scripts"
root = "DumpPortingData"
supportInterpreter = true

[[lean_exe]]
name = "check-imports"
srcDir = "../scripts"
root = "CheckImports"

[leanOptions]
linter.all = false
linter.extra = false
