/-
Copyright (c) 2026 Markus de Medeiros. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Data.Int.Basic
public import Mathlib.Tactic.Ring
public import Iris

/-! # Galois-orbit maps: a non-extensional `LawfulPartialMap`

This file builds a `PartialMap` / `LawfulPartialMap` instance whose stored data carries strictly
more information than its observable denotation: each key is assigned both a value and a *concrete
representative of a quadratic algebraic number*, while `get?` (hence `PartialMap.equiv`) only
observes the value.  Distinct representatives in the same **Galois conjugacy class** therefore give
equal denotations but unequal carriers — the construction is lawful yet **non-extensional**.

It is the direct Galois-theoretic generalization of `IrisMath.OrbitMap`.  Where `OrbitMap` quotients
an integer representative by the *cyclic* additive action of `n·ℤ` (orbits in `ℤ ⧸ n·ℤ ≃ ZMod n`),
`GaloisMap` quotients a representative `a + b√d ∈ ℤ[√d]` by the *Galois* action of
`Gal(ℚ(√d)/ℚ) ≃ ℤ/2`, generated by conjugation `b ↦ -b`.  Both are instances of the same slogan:
**observe a stored representative only up to a group action**; here the group is the order-`2`
Galois group of a quadratic field rather than a cyclic group.

## The Galois / quotient structure

Fix a non-square `d : ℤ`.  An element of the quadratic ring of integers `ℤ[√d]` is a pair
`(a, b) : ℤ × ℤ`, standing for `a + b√d`.  The nontrivial automorphism of `ℚ(√d)/ℚ` is conjugation

  `σ : a + b√d  ↦  a - b√d`,    i.e.    `σ (a, b) = (a, -b)`,

an involution (`σ² = id`) generating `Gal(ℚ(√d)/ℚ) ≃ ℤ/2`.  Its orbits are the **conjugacy
classes** `{(a, b), (a, -b)}`.  The full ring of `σ`-invariants is generated by the two
**Galois invariants**

  trace   `Tr (a, b) = (a + b√d) + (a - b√d) = 2a`,
  norm    `N  (a, b) = (a + b√d)(a - b√d) = a² - d·b²`,

equivalently by the *unordered pair of conjugates*.  Two representatives lie in the same conjugacy
class iff they have the same `(trace, norm)`.

Each stored cell records:

* a *representative* `r = (a, b) : ℤ × ℤ`, only ever observed through its conjugacy class
  `gal r = (Tr r, N r) = (2a, a² - d·b²)` (equivalently `{(a,b), (a,-b)}`), and
* the *value* `v : V` that `get?` returns.

The `ℤ × ℤ` component is invisible to `get?`, which is the source of non-extensionality and of the
Galois frame-preserving updates discussed at the end of the file.

## Design

`GaloisMap d K V := K → Option ((ℤ × ℤ) × V)`.  The first projection is the (unobserved) Galois
representative `a + b√d`; the second is the value returned by `get?`.  The `PartialMap` operations
keep a canonical representative in sync with the value, but only the value is observable.  This
mirrors `IrisMath.OrbitMap`'s `K → Option (ℤ × V)` shape exactly, replacing the integer
orbit-representative by a `ℤ[√d]` Galois-representative and the `ZMod n` orbit observation by the
conjugacy-class observation `gal`.
-/

@[expose] public section

namespace IrisMath

open Iris.Std Iris.Std.PartialMap

variable {K : Type _} [DecidableEq K]

/-- A Galois map for the quadratic field `ℚ(√d)`: each key carries a representative
`a + b√d ∈ ℤ[√d]` (as a pair `(a, b)`) together with its value. -/
def GaloisMap (d : ℤ) (K : Type _) (V : Type _) : Type _ := K → Option ((ℤ × ℤ) × V)

namespace GaloisMap

variable {d : ℤ} {V V' : Type _}

/-- Galois conjugation `σ : a + b√d ↦ a - b√d`, the nontrivial automorphism of `ℚ(√d)/ℚ`.
On representatives it is the involution `(a, b) ↦ (a, -b)` generating `Gal(ℚ(√d)/ℚ) ≃ ℤ/2`. -/
abbrev conj (r : ℤ × ℤ) : ℤ × ℤ := (r.1, -r.2)

/-- Conjugation is an involution: `σ² = id`. -/
@[simp] theorem conj_conj (r : ℤ × ℤ) : conj (conj r) = r := by
  cases r; simp [conj]

/-- The trace `Tr (a + b√d) = (a + b√d) + (a - b√d) = 2a`, a Galois invariant. -/
abbrev trace (r : ℤ × ℤ) : ℤ := 2 * r.1

/-- The norm `N (a + b√d) = (a + b√d)(a - b√d) = a² - d·b²`, a Galois invariant. -/
abbrev norm (r : ℤ × ℤ) : ℤ := r.1 ^ 2 - d * r.2 ^ 2

/-- The observation: send a stored representative `a + b√d` to its **Galois conjugacy class**,
recorded by the pair of Galois invariants `(trace, norm) = (2a, a² - d·b²)`.  This is the
quadratic analogue of `OrbitMap.obs`: it forgets *which* conjugate root is stored, remembering only
the conjugacy class (equivalently the minimal polynomial `X² - (2a)X + (a² - d·b²)`). -/
abbrev gal (r : ℤ × ℤ) : ℤ × ℤ := (trace r, norm (d := d) r)

/-- **Conjugate representatives observe equally.**  A representative and its Galois conjugate have
the same trace and norm, hence the same conjugacy class: `gal (a, b) = gal (a, -b)`. -/
@[simp] theorem gal_conj (r : ℤ × ℤ) : gal (d := d) (conj r) = gal (d := d) r := by
  cases r
  simp only [gal, trace, norm, Prod.mk.injEq, true_and]
  ring

/-! ## The operations.

`get?` reads only the value (second) component; the representative (first) component is carried
along but never observed. -/

/-- Pick a stored representative for a freshly-produced value.  We expose it as a field-free helper
so the operations stay polymorphic in `V`; `get?` never inspects it, so the canonical choice `(0,0)`
(the rational integer `0 + 0√d`) suffices. -/
def rep (d : ℤ) : {V : Type _} → V → ℤ × ℤ := fun _ => (0, 0)

instance instPartialMap : PartialMap (GaloisMap d K) K where
  get? m k := (m k).map Prod.snd
  insert m k v := fun k' => if k = k' then some (rep d v, v) else m k'
  delete m k := fun k' => if k = k' then none else m k'
  empty := fun _ => none
  bindAlter f m := fun k =>
    (m k).bind fun rv => (f k rv.2).map fun v' => (rep d v', v')
  merge op m₁ m₂ := fun k =>
    match m₁ k, m₂ k with
    | none, none => none
    | some x, none => some x
    | none, some y => some y
    | some x, some y => let v := op k x.2 y.2; some (rep d v, v)

/-- The seven `LawfulPartialMap` laws.  Each holds because `get?` is the second projection and
every operation maintains the value component exactly as in the functional model. -/
instance instLawfulPartialMap : LawfulPartialMap (GaloisMap d K) K where
  get?_empty k := rfl
  get?_insert_eq := by simp only [get?, Iris.Std.insert]; grind
  get?_insert_ne := by simp only [get?, Iris.Std.insert]; grind
  get?_delete_eq := by simp only [get?, Iris.Std.delete]; grind
  get?_delete_ne := by simp only [get?, Iris.Std.delete]; grind
  get?_bindAlter := by
    intro V V' k m f
    simp only [get?, bindAlter]
    cases h : m k with
    | none => simp
    | some rv =>
      simp only [Option.map_some, Option.bind_some]
      cases hf : f k rv.2 with
      | none => simp
      | some w => simp
  get?_merge := by
    intro V op m₁ m₂ k
    simp only [get?, merge, Option.merge]
    cases h₁ : m₁ k <;> cases h₂ : m₂ k <;> simp

/-! ## Non-extensionality

We exhibit two carriers that observe identically (`PartialMap.equiv`) but differ as functions:
they store the same value but Galois-*conjugate* representatives `(a, b)` and `(a, -b)`. -/

/-- A one-key map storing value `v` with representative `r = a + b√d`. -/
def cell (k : K) (r : ℤ × ℤ) (v : V) : GaloisMap d K V :=
  fun k' => if k = k' then some (r, v) else none

variable (k : K) (v : V)

/-- **Observational equality.**  Two cells at the same key with the same value are
`PartialMap.equiv` *regardless of the stored representative*: `get?` never sees the `ℤ × ℤ`.  In
particular this holds for Galois-conjugate representatives `(a, b)` and `(a, -b)`. -/
theorem cell_equiv (r r' : ℤ × ℤ) :
    PartialMap.equiv (M := GaloisMap d K) (cell k r v) (cell k r' v) := by
  intro k'
  simp only [get?, cell]
  by_cases h : k = k' <;> simp [h]

/-- **Non-extensionality.**  Galois-conjugate representatives give *distinct carriers*.  For
`b ≠ 0` the representatives `(a, b)` and its conjugate `(a, -b)` are equal under the Galois
observation `gal` (same trace `2a` and norm `a² - d·b²`) yet are distinct in `ℤ × ℤ`, so the cells
are equivalent but unequal. -/
theorem cell_ne {a b : ℤ} (hb : b ≠ 0) (k : K) (v : V) :
    (cell k (a, b) v : GaloisMap d K V) ≠ cell k (a, -b) v := by
  intro hcontra
  have hk := congrFun hcontra k
  simp only [cell, if_true] at hk
  -- `hk : some ((a, b), v) = some ((a, -b), v)`, so the second components of the reps agree.
  have hb' : b = -b := by
    have := (Option.some.injEq _ _).mp hk
    simpa using congrArg (Prod.snd ∘ Prod.fst) this
  omega

/-- The non-extensionality theorem, packaged: two Galois-conjugate representatives `(a, b)` and
`(a, -b)` (with `b ≠ 0`) give a pair of maps that are `PartialMap.equiv` and yet `≠`. -/
theorem nonextensional {a b : ℤ} (hb : b ≠ 0) (k : K) (v : V) :
    PartialMap.equiv (M := GaloisMap d K) (cell k (a, b) v) (cell k (a, -b) v) ∧
      (cell k (a, b) v : GaloisMap d K V) ≠ cell k (a, -b) v :=
  ⟨cell_equiv k v (a, b) (a, -b), cell_ne hb k v⟩

/-- There is no `ExtensionalPartialMap` instance for `GaloisMap`: whenever a non-rational
representative exists (`b ≠ 0`) `equiv` is strictly coarser than `=`, so `equiv_iff_eq` would fail
on the conjugate witnesses above. -/
theorem not_extensional {a b : ℤ} (hb : b ≠ 0) (k : K) (v : V) :
    ¬ (PartialMap.equiv (M := GaloisMap d K) (cell k (a, b) v) (cell k (a, -b) v) →
        (cell k (a, b) v : GaloisMap d K V) = cell k (a, -b) v) :=
  fun h => cell_ne hb k v (h (cell_equiv k v (a, b) (a, -b)))

end GaloisMap

end IrisMath

/-! ## Applicability: Galois maps and the `HeapView` CMRA

Recall `Iris.Algebra.HeapView`: from a `LawfulPartialMap M K` with a CMRA-valued value type one
forms the authoritative/fragment camera `HeapView F K V`, with

* `Auth dq m`   — authoritative ownership of the whole heap `m : M V`, fraction `dq`;
* `Frag k dq v` — fragmentary ownership of key `k` holding value `v`.

The frame-preserving updates `~~>` there (`update_one_alloc`, `update_one_delete`,
`update_replace`, `update_of_local_update`, `update_auth_op_frag`, …; `HeapView.lean` 314–495) all
reduce to *local updates on the value at a single key*, and every relational premise is phrased
through `get?`.  This is exactly where the Galois structure pays off.

### Conjugacy classes are indexed by the Galois invariants `(trace, norm)`

The intended value algebra is the **ring of integers** `ℤ[√d]` itself (a commutative ring, hence a
clean candidate for a heap-style value CMRA), and the logical content of a stored cell is its
*conjugacy class*, recorded by the Galois invariants

  `gal (a, b) = (trace, norm) = (2a, a² - d·b²)`.

A heap that "remembers only Galois-invariant data" stores a representative `a + b√d` but exposes,
through `get?`, only data that is invariant under `Gal(ℚ(√d)/ℚ)`.

### Conjugation is a no-op ⇒ a Galois frame-preserving update

Because `get?` returns only the *value* and never the stored representative `(a, b)`, **any change
to a stored representative is invisible to every `HeapR`/`HeapView` premise**.  The canonical such
change is *replacing a representative by a Galois conjugate*: `σ (a, b) = (a, -b)`.  Since
`gal (conj r) = gal r` (`GaloisMap.gal_conj`), conjugation keeps the conjugacy class — and the
value — fixed.  Concretely, with `m := cell k (a, b) v` and `m' := cell k (a, -b) v` (using
`IrisMath.GaloisMap.cell`):

  `PartialMap.equiv m m'`   (proved here as `GaloisMap.cell_equiv` / `GaloisMap.nonextensional`),

so the induced authoritative element satisfies the frame-preserving update

  `Auth (.own one) m ~~> Auth (.own one) m'`

— it is the identity update up to `equiv`, preserving every premise verbatim because those premises
see only `get?`.  This is a genuinely **Galois-flavored** frame-preserving update: "replace a stored
root by a conjugate root" is observationally inert, realized as a CMRA update.  It is the order-`2`
specialization of the `OrbitMap` slogan "adding a multiple of `n` to a representative is inert";
there the inert action was the cyclic group `ZMod n`, here it is the Galois group `ℤ/2 = ⟨σ⟩`.

### From cyclic orbits to Galois orbits

This file generalizes `IrisMath.OrbitMap` along one axis only — the group acting on the stored
representative:

| construction | representative | acting group | observation (orbit) |
| ------------ | -------------- | ------------ | ------------------- |
| `OrbitMap n` | `z : ℤ`        | `n·ℤ` (cyclic, `ℤ ⧸ n·ℤ ≃ ZMod n`) | `z ↦ (z : ZMod n)` |
| `GaloisMap d`| `(a,b) : ℤ[√d]`| `Gal(ℚ(√d)/ℚ) ≃ ℤ/2 = ⟨σ⟩`         | `(a,b) ↦ (2a, a² - d·b²)` |

Both are "observe a stored representative up to a group action", with the orbit/conjugacy semantics
living entirely in the witnesses and applicability while `get?` stays a bare second projection.  The
cyclic case (`OrbitMap`) and the Galois case (`GaloisMap`) are thus two points on the same design:
non-extensional, quotient-valued partial maps whose hidden representative may drift freely within
its group orbit without affecting any `HeapView` premise.
-/
