/-
Copyright (c) 2026 Yunsong Yang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yunsong Yang, Alvin Tang
-/
module

public meta import Iris.ProofMode.Tactics.Basic
public meta import Iris.ProofMode.Tactics.Assumption
public meta import Iris.ProofMode.Tactics.Cases
public meta import Iris.ProofMode.Patterns.CasesPattern
public meta import Iris.ProofMode.ClassesMake
public meta import Iris.ProofMode.Tactics.RevertIntro

namespace Iris.ProofMode

public meta section
open BI Std Lean Elab Tactic Meta Qq

/--
  The user of the `iinduction` tactic provides the proof for the induction
  subgoal. Induction hypotheses are available for the user in the intuitionistic
  context of the Iris proof state.

  Meanwhile, the actual induction subgoal generated by Lean with the `induction`
  tactic has induction hypotheses in the regular context.

  Given all hypotheses in the Iris proof state (represented by `P`) exist in
  the intuitionistic context (that is, the spatial context is empty), we can
  introduce another induction hypothesis generated by Lean into the
  intuitionistic context.
-/
@[rocq_alias tac_revert_ih]
theorem revert_IH [BI PROP] {P Q : PROP} {φ}
    (ih : φ)
    (h : R ⊢ □ P)
    (inst : IntoIH φ P Q) :
    R ⊢ □ (P ∗ □ Q) := calc
  _ ⊢ □ P         := h
  _ ⊢ □ P ∗ □ P   := intuitionistically_sep_dup.mp
  _ ⊢ □ P ∗ □ □ P := sep_mono_r intuitionistically_idem.mpr
  _ ⊢ □ P ∗ □ Q   := sep_mono_r <| intuitionistically_mono <| inst.into_ih ih
  _ ⊢ □ P ∗ □ □ Q := sep_mono_r intuitionistically_idem.mpr
  _ ⊢ □ (P ∗ □ Q) := intuitionistically_sep_2

/--
  Designed to be a mutable state such that `newHyps` contains induction
  hypotheses generated by Lean's built-in induction.
-/
private structure InductionState {u} {prop : Q(Type u)} {bi} (origE : Q($prop)) where
  {newE : Q($prop)}
  (newHyps : Hyps bi newE)
  (pf : Q($origE ⊢ □ $newE))

/--
  Given a collection of hypotheses (`hyps`) and a free variable `fvar`, return
  the subset of intuitionistic hypotheses in `hyps` that contains the `fvar`
  and all spatial hypotheses in the proof state.

  This function is used for identifying the hypotheses in the Iris proof state
  that must be reverted before applying Lean's built-in `induction` tactic.
-/
private def iHypsContaining {u} {prop : Q(Type $u)} {bi} {e : Q($prop)}
    (hyps : Hyps bi e) (fvars : List FVarId) : List SelTarget :=
  let ivars := hyps.intuitionisticIVarIds.filter <| fun ivar =>
    match hyps.getDecl? ivar with
    | some ⟨_, _, _, ty⟩ => fvars.any ty.containsFVar
    | none => false

  (ivars ++ hyps.spatialIVarIds).map ({ kind := .ipm ·, explicit := false })

/--
  Search for hypotheses in the regular Lean context that represent induction
  hypotheses and return their IDs as a list.
-/
private def findIHs (m : MVarId) : ProofModeM (List FVarId) :=
  m.withContext do
    let lctx ← getLCtx
    let mut ihs := []
    for decl in lctx do
      let type ← instantiateMVars decl.type
      if isIrisGoalWithForalls type then
        ihs := decl.fvarId :: ihs
    return ihs.reverse

/--
  Used for every induction hypothesis generated by Lean upon using the built-in
  `induction` tactic. This function is called by `addIHs` and returns
  an instance of `InductionState` after handling one induction hypothesis.
-/
private def addIH {u} {prop : Q(Type u)} {bi : Q(BI $prop)} {e}
    (st : @InductionState u prop bi e)
    (φ : Q(Prop)) (p : Q($φ)) (hFVar : FVarId) :
    ProofModeM (@InductionState u prop bi e) := do
  let oldE := st.newE
  let oldHyps : Hyps bi oldE := st.newHyps

  -- Obtain the proposition to be introduced into the intuitionistic context
  let Q ← mkFreshExprMVarQ q($prop)
  let some inst ← ProofModeM.trySynthInstanceQ q(IntoIH $φ $oldE $Q)
  | throwError "iinduction: type class synthesis with IntoIH failed"

  -- Introduce the induction hypothesis into the intuitionistic context
  let nameIdent := mkIdent <| ← hFVar.getUserName
  let binderIdent ← `(binderIdent| $nameIdent:ident)
  let ⟨_, newHyps⟩ ← Hyps.addWithInfo bi binderIdent q(true) Q oldHyps

  return { newHyps, pf := q(revert_IH $p $st.pf $inst) }

/--
  Introduce a list of induction hypotheses into the intuitionistic context
  of the Iris proof state. The list of `FVarId` values (`ihFVars`) should be
  the list returned by `findIHs`. The function returns the final
  `InductionState` with all induction hypotheses handled.

  The argument `pfIntHyps` holds when the spatial context is empty, which
  is indeed the case when all hypotheses therein have been reverted.
-/
private def addIHs {u} {prop : Q(Type u)} {bi : Q(BI $prop)} {e : Q($prop)}
    (pfIntHyps : Q($e ⊢ □ $e)) (hyps : Hyps bi e) (ihFVars : List FVarId) :
    ProofModeM (@InductionState u prop bi e) := do

  -- Initialise the mutable instance of `InductionState`
  let mut st : InductionState e := { newHyps := hyps, pf := q($pfIntHyps) }

  -- Iteratively move the induction hypotheses into the intuitionistic context
  for i in ihFVars do
    let p := mkFVar i
    let φ ← inferType <| mkFVar i
    st ← addIH st φ p i

  return st

/--
  Given hypothesis `hyps` representing `e` where every hypothesis exist in the
  intuitionistic context, return the proof of `e ⊢ □ e`. Throw an error if
  `hyps` contains hypotheses in the spatial context.
-/
private def buildPfIntHyps {u} {prop : Q(Type u)} {bi : Q(BI $prop)} {e}
    (hyps : Hyps bi e) : ProofModeM Q($e ⊢ □ $e) :=
  match hyps with
  | .emp _ => pure q(intuitionistically_emp.mpr)
  | .hyp _ _ _ p _ _ =>
    match matchBool p with
    | .inl _ => pure q(intuitionistically_idem.mpr)
    | .inr _ =>
      throwError "iinduction: spatial context is not empty after reverting hypotheses"
  | .sep _ _ _ _ lhs rhs => do
    let pfL ← buildPfIntHyps lhs
    let pfR ← buildPfIntHyps rhs
    pure q((sep_mono $pfL $pfR).trans intuitionistically_sep_2)

/--
  Tactic syntax for user-supplied alternative names.
-/
syntax inductionAlts := "| " binderIdent+ " => " tacticSeq

/--
  Parse the tactic syntax for user-supplied alternative names.

  This function returns a triple, which includes:
  1. the name of the constructor supplied by the user (`ctor.getId`),
  2. the alternative names for that constructor (`vars`), and
  3. the tactics for this induction subgoal.
-/
private def parseInductionAlts (alt : TSyntax `Iris.ProofMode.inductionAlts) :
    TacticM (Name × Array (TSyntax `Lean.binderIdent) × TSyntax `Lean.Parser.Tactic.tacticSeq) := do
  let `(inductionAlts| | $ctor:ident $vars:binderIdent* => $tac:tacticSeq) := alt
  | throwError "iinduction: invalid syntax"
  return ⟨ctor.getId, vars, tac⟩

/--
  Check whether a fully-qualified constructor name (e.g. `Nat.succ`) matches a
  user-written short name (e.g. `succ`) or an already-qualified name.
-/
private def matchesCtorName (fullName : Name) (userShort : Name) : Bool :=
  fullName == userShort || fullName.getString! == userShort.getString!

/--
  Throw an error if the user has supplied some but not all alternative names.
-/
private def throwMissingAlt {α} (ctor : Name) : ProofModeM α :=
  throwError "iinduction: alternative `{ctor.getString!}` has not been provided"

/--
  Checks whether an invalid, missing and/or duplicate constructor names have
  been supplied by the user. Throw an error if this is the case.
-/
private def checkCtors (ctors altCtors : List Name) : ProofModeM Unit := do
  let mut errors : List String := []

  -- Check for missing constructor names
  let missingAltCtors :=
    ctors.filter (not <| altCtors.any <| fun altCtor => matchesCtorName · altCtor)

  -- Check for invalid constructor names
  let invalidAltCtors :=
    altCtors.filter (not <| ctors.any <| fun ctor => matchesCtorName ctor ·)

  -- Check for duplicate constructor names
  let dupAltCtors := (altCtors.filter (fun alt => altCtors.countP (fun alt' => matchesCtorName alt alt') > 1)).eraseDupsBy matchesCtorName

  if !missingAltCtors.isEmpty then
    let missing := ", ".intercalate  <| missingAltCtors.map (s!"`{·}`")
    errors := errors.concat s!"iinduction: missing alternative name(s): {missing}"
  if !dupAltCtors.isEmpty then
    let dups := ", ".intercalate  <| dupAltCtors.map (s!"`{·}`")
    errors := errors.concat s!"iinduction: duplicate alternative name(s): {dups}"
  if !invalidAltCtors.isEmpty then
    let invalids := ", ".intercalate <| invalidAltCtors.map (s!"`{·}`")
    errors := errors.concat s!"iinduction: invalid alternative name(s): {invalids}"

  if !errors.isEmpty then
    throwError m!"{"\n".intercalate errors}"

/--
  The main function handling the steps for the `iinduction` tactic.

  1. Revert Iris hypotheses explicitly specified by the tactic user
     (applicable when the `generalizing` syntax is used).
  2. Revert all spatial hypotheses in the Iris proof state as well as the
     relevant hypotheses in the intuitionistic context.
  3. Revert pure Lean variables specified by the tactic user
     (applicable when the `generalizing` syntax is used).
  4. Prepare the arguments for `Lean.Meta.Tactic.induction`.
  5. Apply `Lean.Meta.Tactic.induction` to obtain the induction subgoals.
  6. For each subgoal, move the induction hypotheses from the regular Lean
     context into the Iris intuitionistic context.
  7. Introduce hypotheses reverted in steps 1 and 2 back into the Iris proof state.

  The relevant intuitionistic hypotheses to which Step 2 refers are those
  involving `fvar` or pure Lean variables in `genSelTargets`.
-/
private def iInductionCore {u} {prop : Q(Type u)} {bi : Q(BI $prop)} {e}
    (hyps : Hyps bi e) (goal : Q($prop)) (fvar : FVarId)
    (parsedAlts : Option <| Array <| Name × Array (TSyntax `Lean.binderIdent) × TSyntax `Lean.Parser.Tactic.tacticSeq)
    (altRecName : Option Name)
    (genSelTargets : Option <| List SelTarget) :
    ProofModeM Q($e ⊢ $goal) := do
  -- Iris hypotheses to be reverted as specified by the user using the `generalizing` syntax
  let explicitIrisTargets : List SelTarget :=
    match genSelTargets with
    | none => []
    | some genSelTargets => genSelTargets.filter <| fun t => match t.kind with | .ipm _ => true | _ => false

  -- `FVarID` values of pure hypothesis specified by the user using the `generalizing` syntax
  let pureFVars : List FVarId :=
    match genSelTargets with
    | none => []
    | some genSelTargets =>
      genSelTargets.filterMap <| fun t => match t.kind with | .pure f => some f | _ => none

  -- Iris hypotheses in the spatial context and relevant intuitionistic context
  let spatialAndIntuitionisticTargets := iHypsContaining hyps <| pureFVars.concat fvar

  let spatialAndIntuitionisticTargets :=
    spatialAndIntuitionisticTargets.filter (not <| (explicitIrisTargets.map (·.kind)).contains ·.kind)

  -- Pure hypotheses to be reverted as specified by the user using the `generalizing` syntax
  let pureTargets : List SelTarget := pureFVars.map ({ kind := .pure ·, explicit := true })

  -- Those in `explicitIrisTargets` get reverted first, so they are last in the list
  let targets := pureTargets ++ spatialAndIntuitionisticTargets ++ explicitIrisTargets

  -- Find the recursor name and constructor names of the inductive datatype
  let fvarType ← whnf <| ← inferType <| mkFVar fvar
  let ⟨recName, ctors⟩ ← match fvarType.getAppFn with
  | .const indName _ =>
    match (← getEnv).find? indName with
    | some (.inductInfo val) =>
        -- Use the user-supplied recursor name if available
        let some recName ← match altRecName with
          | none => getCustomEliminator? #[mkFVar fvar] true
          | some altRecName => pure altRecName
        | throwError "iinduction: unable to determine recursor name"
        pure (recName, val.ctors)
    | _ => throwError "iinduction: {indName} is not inductive"
  | _ => throwError "iinduction: unable to determine inductive type"

  let matcher :
    Name →
    Name × Array (TSyntax `Lean.binderIdent) × TSyntax `Lean.Parser.Tactic.tacticSeq →
    Bool := fun ctor ⟨altCtor, _, _⟩ => matchesCtorName ctor altCtor

  -- Check that all alternative names supplied by the user are valid
  match parsedAlts with
  | none => pure ()
  | some parsedAlts => checkCtors ctors <| parsedAlts.toList.map Prod.fst

  -- Define the names for variables and induction hypotheses if supplied by user
  let varNames : Array AltVarNames ←
    match parsedAlts with
    | none =>
      pure <| ctors.toArray.map <| fun _ => { explicit := true, varNames := [] }
    | some parsedAlts => do
      ctors.toArray.mapM <| fun ctor =>
      match parsedAlts.find? <| matcher ctor with
      | some (_, vars, _) =>
        pure { explicit := true, varNames := vars.toList.map <|
          fun v =>
            match v.raw with
            | `(binderIdent| $id:ident) => id.getId
            | _ => Name.mkSimple "_" }
      | none => throwMissingAlt ctor

  let pf ← iRevertIntro hyps goal targets <|
    fun hyps' goal' k => do
      -- Create a new metavariable for the proof goal upon reverting hypotheses
      let m ← mkBIGoal hyps' goal'

      -- Use built-in induction in Lean to generate the subgoals for induction
      let subgoals ←  m.mvarId!.withContext do
        m.mvarId!.induction fvar recName varNames

      -- Handle each subgoal generated by Lean's induction
      for ⟨s, ctor⟩ in subgoals.toList.zip ctors do
        s.mvarId.withContext do
          -- For pretty printing of arguments
          match parsedAlts with
          | none => pure ()
          | some parsedAlts =>
            match parsedAlts.find? <| matcher ctor with
            | some ⟨_, vars, _⟩ =>
              for ⟨fieldFVar, varStx⟩ in s.fields.toList.zip vars.toList do
                if let `(binderIdent| $id:ident) := varStx then
                  let lctx ← getLCtx
                  let fieldType ← inferType fieldFVar
                  addLocalVarInfo id lctx fieldFVar (some fieldType) true
            | none => throwMissingAlt ctor

          -- Obtain the type of the induction subgoal
          let sType ← instantiateMVars <| ← s.mvarId.getType

          let some irisGoal := parseIrisGoal? sType
          -- This should not happen
          | throwError "iinduction: fail to parse induction subgoal"

          -- Find the induction hypotheses generated by Lean's `induction` tactic
          let ihFVars ← findIHs s.mvarId

          -- A proof that all hypotheses in the Iris goal exist in the intuitionistic context
          let pfIntHyps ← buildPfIntHyps irisGoal.hyps

          -- Introduce the induction hypothesis back into the Iris proof state
          let st ← addIHs pfIntHyps irisGoal.hyps ihFVars

          -- Generate the induction subgoal for the user
          let pf' ← withoutFVars (u := 0) ihFVars.toArray <| k st.newHyps irisGoal.goal

          -- Fill the metavariable for the induction subgoal generated by Lean
          s.mvarId.assign <| q($(st.pf).trans <| intuitionistically_elim.trans $pf')

          -- Handle user-supplied tactics for specific constructors
          match parsedAlts with
          | none => pure ()
          | some parsedAlts =>
            let biGoalMVar := (← getThe ProofModeM.State).goals.back!
            modify <| fun s => { s with goals := s.goals.pop }

            let some ⟨_, _, userTac⟩ := parsedAlts.find? <| matcher ctor
            | throwMissingAlt ctor

            -- Run the user tactic on the BI goal
            let savedGoals ← getGoals
            setGoals [biGoalMVar]
            evalTactic userTac
            let remaining ← getGoals
            setGoals savedGoals
            for r in remaining do addMVarGoal r

      return m

  return pf

/--
  Given a term expression, check whether it is a `FVarId` value. If so,
  return it directly. Otherwise, generalise the term expressions before
  returning its `FVarId`.
-/
private def termToFVar (x : TSyntax `term) : TacticM FVarId := do
  let e ← withMainContext <| elabTerm x none
  let e ← instantiateMVars e

  if e.isFVar then
    return e.fvarId!

  let mvarId ← getMainGoal
  let (fvars, newMVarId) ← mvarId.generalize #[{ expr := e }]
  replaceMainGoal [newMVarId]

  return fvars[0]!

/--
  Simple tactic with inaccessible names of variables and induction hypotheses
  generated by Lean automatically.
-/
elab "iinduction" colGt x:term : tactic => do
  let fvar ← termToFVar x

  ProofModeM.runTactic λ mvar { hyps, goal, .. } => do
    let pf ← iInductionCore hyps goal fvar none none none
    mvar.assign pf

/-- Tactic with names of variables and induction hypotheses supplied by the user. -/
elab "iinduction" colGt x:term "with" alts:(colGe inductionAlts)* : tactic => do
  let fvar ← termToFVar x

  -- Parse the list of alternative names supplied by the user
  let parsedAlts ← alts.mapM parseInductionAlts

  ProofModeM.runTactic λ mvar { hyps, goal, .. } => do
    let pf ← iInductionCore hyps goal fvar parsedAlts none none
    mvar.assign pf

/-- Tactic with the recursor name supplied by the user. -/
elab "iinduction" colGt x:term "using" r:ident : tactic => do
  let fvar ← termToFVar x

  -- Parse the recursor name provided by the user
  let recName := r.getId

  ProofModeM.runTactic λ mvar { hyps, goal, .. } => do
    let pf ← iInductionCore hyps goal fvar none recName none
    mvar.assign pf

/-- Tactic with the recursor name and alternative names supplied by the user. -/
elab "iinduction" colGt x:term "using" r:ident "with" alts:(colGe inductionAlts)* : tactic => do
  let fvar ← termToFVar x

  -- Parse the recursor name provided by the user
  let recName := r.getId
  -- Parse the list of alternative names supplied by the user
  let parsedAlts ← alts.mapM parseInductionAlts

  ProofModeM.runTactic λ mvar { hyps, goal, .. } => do
    let pf ← iInductionCore hyps goal fvar parsedAlts recName none
    mvar.assign pf

elab "iinduction" colGt x:term "generalizing" genSelPats:(colGt selPat)+ : tactic => do
  let fvar ← termToFVar x

  ProofModeM.runTactic λ mvar { hyps, goal, .. } => do
    -- Parse the user-supplied list of variables to be generalised
    let genSelPats ← liftMacroM <| SelPat.parse genSelPats
    let genSelTargets ← SelPat.resolve hyps genSelPats

    let pf ← iInductionCore hyps goal fvar none none genSelTargets
    mvar.assign pf

elab "iinduction" colGt x:term "generalizing" genSelPats:(colGt selPat)+ "with" alts:(colGe inductionAlts)* : tactic => do
  let fvar ← termToFVar x

  -- Parse the list of alternative names supplied by the user
  let parsedAlts ← alts.mapM parseInductionAlts

  ProofModeM.runTactic λ mvar { hyps, goal, .. } => do
    -- Parse the user-supplied list of variables to be generalised
    let genSelPats ← liftMacroM <| SelPat.parse genSelPats
    let genSelTargets ← SelPat.resolve hyps genSelPats

    let pf ← iInductionCore hyps goal fvar parsedAlts none genSelTargets
    mvar.assign pf

elab "iinduction" colGt x:term "using" r:ident "generalizing" genSelPats:(colGt selPat)+ : tactic => do
  let fvar ← termToFVar x

  -- Parse the recursor name provided by the user
  let recName := r.getId

  ProofModeM.runTactic λ mvar { hyps, goal, .. } => do
    -- Parse the user-supplied list of variables to be generalised
    let genSelPats ← liftMacroM <| SelPat.parse genSelPats
    let genSelTargets ← SelPat.resolve hyps genSelPats

    let pf ← iInductionCore hyps goal fvar none recName genSelTargets
    mvar.assign pf

elab "iinduction" colGt x:term "using" r:ident "generalizing" genSelPats:(colGt selPat)+ "with" alts:(colGe inductionAlts)* : tactic => do
  let fvar ← termToFVar x

  -- Parse the recursor name provided by the user
  let recName := r.getId
  -- Parse the list of alternative names supplied by the user
  let parsedAlts ← alts.mapM parseInductionAlts

  ProofModeM.runTactic λ mvar { hyps, goal, .. } => do
    -- Parse the user-supplied list of variables to be generalised
    let genSelPats ← liftMacroM <| SelPat.parse genSelPats
    let genSelTargets ← SelPat.resolve hyps genSelPats

    let pf ← iInductionCore hyps goal fvar parsedAlts recName genSelTargets
    mvar.assign pf
