/-
Copyright (c) 2026 Yunsong Yang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yunsong Yang, Alvin Tang
-/
module

public meta import Iris.ProofMode.Tactics.Basic
public meta import Iris.ProofMode.Tactics.Assumption
public meta import Iris.ProofMode.Tactics.Cases
public meta import Iris.ProofMode.Patterns.CasesPattern
public meta import Iris.ProofMode.ClassesMake
public meta import Iris.ProofMode.Tactics.RevertIntro

namespace Iris.ProofMode

public meta section
open BI Std Lean Elab Tactic Meta Qq

/--
  Tactic syntax for user-supplied alternative names.
-/
syntax inductionAlt := "| " binderIdent+ " => " tacticSeq

/--
  Parse the tactic syntax for user-supplied alternative names.

  This function returns a triple, which includes:
  1. the name of the constructor supplied by the user (`ctor.getId`),
  2. the alternative names for that constructor (`vars`), and
  3. the tactics for this induction subgoal.
-/
private def parseinductionAlt (alt : TSyntax `Iris.ProofMode.inductionAlt) :
    TacticM (Name × Array (TSyntax `Lean.binderIdent) × TSyntax `Lean.Parser.Tactic.tacticSeq) := do
  let `(inductionAlt| | $ctor:ident $vars:binderIdent* => $tac:tacticSeq) := alt
  | throwError "iinduction: invalid syntax"
  return ⟨ctor.getId, vars, tac⟩

/--
  Check whether a fully-qualified constructor name (e.g. `Nat.succ`) matches a
  user-written short name (e.g. `succ`) or an already-qualified name.
-/
private def matchesCtorName (fullName : Name) (userShort : Name) : Bool :=
  fullName == userShort || fullName.getString! == userShort.getString!

/--
  This theorem is used for updating the proof in `InductionState` as `addIHs`
  iterates through the list of induction hypotheses and introduces them from
  the regular Lean context into the intuitionistic context.

  The initial set of hypotheses that exist in the Iris context after applying
  Lean's built-in induction step is represented by `P`. Since the spatial
  context is empty (that is, all hypotheses exist in intuitionistic context),
  `P ⊢ □ P` must hold.

  The proposition `Q` represents these initial hypotheses as well as induction
  hypotheses introduced into the intuitionistic context up until the most
  recent `addIHs` iteration. At every iteration of `addIHs`, an induction
  hypothesis `R` is obtained upon type class synthesis with `IntoIH`. The proof
  for `InductionState` is obtained using this theorem accordingly.
-/
@[rocq_alias tac_revert_ih]
theorem revert_IH [BI PROP] {P Q R : PROP} {φ}
    (ih : φ)
    (h1 : P ⊢ □ P)
    (h2 : P ⊢ Q)
    (inst : IntoIH φ P R) :
    P ⊢ (Q ∗ □ R) := calc
  _ ⊢ □ P         := h1
  _ ⊢ □ P ∗ □ P   := intuitionistically_sep_dup.mp
  _ ⊢ □ P ∗ □ □ P := sep_mono_r intuitionistically_idem.mpr
  _ ⊢ □ P ∗ □ R   := sep_mono_r <| intuitionistically_mono <| inst.into_ih ih
  _ ⊢ □ Q ∗ □ R   := sep_mono_l <| intuitionistically_mono h2
  _ ⊢ Q ∗ □ R     := sep_mono_l intuitionistically_elim

/--
  Designed to be a mutable state such that `newHyps` contains induction
  hypotheses generated by Lean's built-in induction.
-/
private structure InductionState {u} {prop : Q(Type u)} {bi} (origE : Q($prop)) where
  {newE : Q($prop)}
  (newHyps : Hyps bi newE)
  (pf : Q($origE ⊢ $newE))

/--
  Given a collection of hypotheses (`hyps`) and a free variable `fvar`
  representing the variable on which induction is applied, return the subset of
  hypotheses in the Iris goal to be generalised. This includes the subset of
  hypotheses in the intuitionistic context with occurrences of `fvar`, as well
  as all spatial hypotheses.

  These hypotheses are then reverted from the the Iris contexts into the regular
  Lean context before applying Lean's built-in `induction` tactic.
-/
private def iHypsToGeneralize {u} {prop : Q(Type $u)} {bi} {e : Q($prop)}
    (hyps : Hyps bi e) (fvars : List FVarId) : List SelTarget :=
  let ivars := hyps.intuitionisticIVarIds.filter <| fun ivar =>
    match hyps.getDecl? ivar with
    | some ⟨_, _, _, ty⟩ => fvars.any ty.containsFVar
    | none => false

  (ivars ++ hyps.spatialIVarIds).map ({ kind := .ipm ·, explicit := false })

/--
  Search for hypotheses in the regular Lean context that are the in the form
  of Iris goals. These must be induction hypotheses generated by Lean's built-in
  `induction` tactic, as there would otherwise not be Iris goals as assumptions
  in the regular context.
-/
private def findIHs (m : MVarId) : ProofModeM (List FVarId) :=
  m.withContext do
    let lctx ← getLCtx
    let mut ihs := []
    for decl in lctx do
      let type ← instantiateMVars decl.type
      if isIrisGoal type.getForallBody then
        ihs := decl.fvarId :: ihs
    return ihs.reverse

/--
  Introduce a list of induction hypotheses into the intuitionistic context
  of the Iris proof state. The list of `FVarId` values (`ihFVars`) should be
  the list returned by `findIHs`. The function returns the final
  `InductionState` with all induction hypotheses handled.

  The argument `intuitionsiticProof` is obtained from the fact that the spatial
  context is empty, which is indeed the case when all hypotheses therein have
  been reverted into the regular Lean context.
-/
private def addIHs {u} {prop : Q(Type u)} {bi : Q(BI $prop)} {e : Q($prop)}
    (pfIntHyps : Q($e ⊢ □ $e)) (hyps : Hyps bi e) (ihFVars : List FVarId) :
    ProofModeM (@InductionState u prop bi e) := do

  -- Initialise the mutable instance of `InductionState`
  let mut st : InductionState e := { newHyps := hyps, pf := q(.rfl) }

  -- Iteratively move the induction hypotheses into the intuitionistic context
  for i in ihFVars do
    let ⟨_u, (ϕ : Q(Prop)), (p : Q($ϕ))⟩ ← inferTypeQ <| mkFVar i

    -- Obtain the proposition to be introduced into the intuitionistic context
    let Q ← mkFreshExprMVarQ q($prop)
    let some inst ← ProofModeM.trySynthInstanceQ q(IntoIH $ϕ $e $Q)
    | throwError m!"iinduction: unable to perform type class synthesis with IntoIH for the induction hypothesis {ϕ}"

    -- Introduce the induction hypothesis into the intuitionistic context
    let nameIdent := mkIdent <| ← i.getUserName
    let binderIdent ← `(binderIdent| $nameIdent:ident)
    let ⟨_, newHyps⟩ ← Hyps.addWithInfo bi binderIdent q(true) Q st.newHyps
    let pf := q(revert_IH $p $pfIntHyps $st.pf $inst)

    st := { newHyps, pf }

  return st

/--
  Throw an error if the user has supplied some but not all alternative names.
-/
private def throwMissingAlt {α} (ctor : Name) : ProofModeM α :=
  throwError "iinduction: alternative `{ctor.getString!}` has not been provided"

/--
  Checks whether an invalid, missing and/or duplicate constructor names have
  been supplied by the user. Throw an error if this is the case.
-/
private def checkCtors (ctors altCtors : List Name) : ProofModeM Unit := do
  let mut errors : List String := []

  -- Check for missing constructor names
  let missingAltCtors :=
    ctors.filter (not <| altCtors.any <| fun altCtor => matchesCtorName · altCtor)

  -- Check for invalid constructor names
  let invalidAltCtors :=
    altCtors.filter (not <| ctors.any <| fun ctor => matchesCtorName ctor ·)

  -- Check for duplicate constructor names
  let dupAltCtors := (altCtors.filter <|
    fun alt => altCtors.countP (matchesCtorName alt ·) > 1).eraseDupsBy matchesCtorName

  if !missingAltCtors.isEmpty then
    let missing := ", ".intercalate  <| missingAltCtors.map (s!"`{·}`")
    errors := errors.concat s!"iinduction: missing alternative name(s): {missing}"
  if !dupAltCtors.isEmpty then
    let dups := ", ".intercalate  <| dupAltCtors.map (s!"`{·}`")
    errors := errors.concat s!"iinduction: duplicate alternative name(s): {dups}"
  if !invalidAltCtors.isEmpty then
    let invalids := ", ".intercalate <| invalidAltCtors.map (s!"`{·}`")
    errors := errors.concat s!"iinduction: invalid alternative name(s): {invalids}"

  if !errors.isEmpty then
    throwError m!"{"\n".intercalate errors}"

/--
  The main function handling the steps for the `iinduction` tactic.

  1. Revert Iris hypotheses explicitly specified by the tactic user
     (applicable when the `generalizing` syntax is used).
  2. Revert all spatial hypotheses in the Iris proof state as well as the
     relevant hypotheses in the intuitionistic context.
  3. Revert pure Lean variables specified by the tactic user
     (applicable when the `generalizing` syntax is used).
  4. Prepare the arguments for `Lean.Meta.Tactic.induction`.
  5. Apply `Lean.Meta.Tactic.induction` to obtain the induction subgoals.
  6. For each subgoal, move the induction hypotheses from the regular Lean
     context into the Iris intuitionistic context.
  7. Introduce hypotheses reverted in steps 1 and 2 back into the Iris proof state.

  The relevant intuitionistic hypotheses to which Step 2 refers are those
  involving `fvar` or pure Lean variables in `genSelTargets`.
-/
private def iInductionCore {u} {prop : Q(Type u)} {bi : Q(BI $prop)} {e}
    (hyps : Hyps bi e) (goal : Q($prop)) (fvar : FVarId)
    (parsedAlts : Option <| Array <|
      Name × Array (TSyntax `Lean.binderIdent) × TSyntax `Lean.Parser.Tactic.tacticSeq)
    (altRecName : Option Name)
    (genSelTargets : Option <| List SelTarget) :
    ProofModeM Q($e ⊢ $goal) := do
  -- Iris hypotheses to be reverted as specified by the user using the `generalizing` syntax
  let explicitIrisTargets : List SelTarget :=
    match genSelTargets with
    | none => []
    | some genSelTargets => genSelTargets.filter <| fun t => match t.kind with | .ipm _ => true | _ => false

  -- `FVarID` values of pure hypothesis specified by the user using the `generalizing` syntax
  let pureFVars : List FVarId :=
    match genSelTargets with
    | none => []
    | some genSelTargets =>
      genSelTargets.filterMap <| fun t => match t.kind with | .pure f => some f | _ => none

  -- Iris hypotheses in the spatial context and relevant intuitionistic context
  let spatialAndIntuitionisticTargets := iHypsToGeneralize hyps <| pureFVars.concat fvar

  let spatialAndIntuitionisticTargets :=
    spatialAndIntuitionisticTargets.filter (not <| (explicitIrisTargets.map (·.kind)).contains ·.kind)

  -- Pure hypotheses to be reverted as specified by the user using the `generalizing` syntax
  let pureTargets : List SelTarget := pureFVars.map ({ kind := .pure ·, explicit := true })

  -- Those in `explicitIrisTargets` get reverted first, so they are last in the list
  let targets := pureTargets ++ spatialAndIntuitionisticTargets ++ explicitIrisTargets

  -- Find the recursor name and constructor names of the inductive datatype
  let fvarType ← whnf <| ← inferType <| mkFVar fvar
  let recName ← match fvarType.getAppFn with
  | .const indName _ =>
    match (← getEnv).find? indName with
    | some (.inductInfo _) =>
        let recName ←
          match altRecName, ← getCustomEliminator? #[mkFVar fvar] true with
          -- Use the user-supplied recursor name if available
          | some altRecName, _ => pure altRecName
          -- Use the default recursor name if available
          | none, some r => pure r
          -- Use `.rec` as the fallback option
          | none, none => pure <| mkRecName indName
        pure recName
    | _ => throwError "iinduction: {indName} is not inductive"
  | _ => throwError "iinduction: unable to determine inductive type"

  let matcher :
    Name →
    Name × Array (TSyntax `Lean.binderIdent) × TSyntax `Lean.Parser.Tactic.tacticSeq →
    Bool := fun ctor ⟨altCtor, _, _⟩ => matchesCtorName ctor altCtor

  -- Find the constructor names
  let caseNames := ((← Lean.Meta.getElimInfo recName).altsInfo.map (·.name)).toList

  -- Check that all alternative names supplied by the user are valid
  match parsedAlts with
  | none => pure ()
  | some parsedAlts => checkCtors caseNames <| parsedAlts.toList.map Prod.fst

  -- Define the names for variables and induction hypotheses if supplied by user
  let varNames : Array AltVarNames ←
    match parsedAlts with
    | none =>
      pure <| caseNames.toArray.map <| fun _ => { explicit := true, varNames := [] }
    | some parsedAlts => do
      caseNames.toArray.mapM <| fun ctor =>
      match parsedAlts.find? <| matcher ctor with
      | some (_, vars, _) =>
        pure { explicit := true, varNames := vars.toList.map <|
          fun v =>
            match v.raw with
            | `(binderIdent| $id:ident) => id.getId
            | _ => Name.mkSimple "_" }
      | none => throwMissingAlt ctor

  let pf ← iRevertIntro hyps goal targets <|
    fun hyps' goal' k => do
      -- Create a new metavariable for the proof goal upon reverting hypotheses
      let m ← mkBIGoal hyps' goal'

      -- Use built-in induction in Lean to generate the subgoals for induction
      let subgoals ←  m.mvarId!.withContext do
        m.mvarId!.induction fvar recName varNames

      -- Handle each subgoal generated by Lean's induction
      for ⟨s, ctor⟩ in subgoals.toList.zip caseNames do
        s.mvarId.withContext do
          -- For pretty printing of arguments
          match parsedAlts with
          | none => pure ()
          | some parsedAlts =>
            s.mvarId.setTag ctor
            match parsedAlts.find? <| matcher ctor with
            | some ⟨_, vars, _⟩ =>
              if vars.size > s.fields.size then
                throwError
                  s!"iinduction: too many variable names provided at alternative `{ctor}`: ".append
                  s!"{vars.size} provided, but {s.fields.size} expected"
              for ⟨fieldFVar, varStx⟩ in s.fields.toList.zip vars.toList do
                if let `(binderIdent| $id:ident) := varStx then
                  let lctx ← getLCtx
                  let fieldType ← inferType fieldFVar
                  addLocalVarInfo id lctx fieldFVar (some fieldType) true
            | none => throwMissingAlt ctor

          -- Obtain the type of the induction subgoal
          let sType ← instantiateMVars <| ← s.mvarId.getType

          let some irisGoal := parseIrisGoal? sType
          -- This should not happen
          | throwError "iinduction: fail to parse induction subgoal"

          -- Find the induction hypotheses generated by Lean's `induction` tactic
          let ihFVars ← findIHs s.mvarId

          -- A proof that all hypotheses in the Iris goal exist in the intuitionistic context
          let some pfIntHyps := irisGoal.hyps.buildIntuitionisticProof
          | throwError "iinduction: spatial context should be empty"

          -- Introduce the induction hypothesis back into the Iris proof state
          let st ← addIHs pfIntHyps irisGoal.hyps ihFVars

          -- Generate the induction subgoal for the user, label the induction subgoal with `ctor`
          let pf' ← withoutFVars (u := 0) ihFVars.toArray <| k st.newHyps irisGoal.goal (addBIGoal · · ctor)

          -- Fill the metavariable for the induction subgoal generated by Lean
          s.mvarId.assign <| q($(st.pf).trans $pf')

          let biGoalMVar := (← getThe ProofModeM.State).goals.back!

          -- Handle user-supplied tactics for specific constructors
          match parsedAlts with
          | none => pure ()
          | some parsedAlts =>
            modify <| fun s => { s with goals := s.goals.pop }

            let some ⟨_, _, userTac⟩ := parsedAlts.find? <| matcher ctor
            | throwMissingAlt ctor

            -- Run the user tactic on the BI goal
            let savedGoals ← getGoals
            setGoals [biGoalMVar]
            evalTactic userTac
            let remaining ← getGoals
            setGoals savedGoals
            for r in remaining do addMVarGoal r

      return m

  return pf

/--
  Given a term expression, check whether it is a `FVarId` value. If so,
  return it directly. Otherwise, generalise the term expression before
  returning its `FVarId`. This function has to be called before entering
  `ProofModeM`, as it directly replaces the metavariable for the current
  proof goal.
-/
private def generalizeTermWithFVar (x : TSyntax `term) : TacticM FVarId := do
  let e ← withMainContext <| elabTerm x none
  let e ← instantiateMVars e

  if e.isFVar then
    return e.fvarId!

  let mvarId ← getMainGoal
  let (fvars, newMVarId) ← mvarId.generalize #[{ expr := e }]
  replaceMainGoal [newMVarId]

  return fvars[0]!

syntax (name := iinduction) "iinduction" colGt term
    ("using" ident)?
    ("generalizing" (colGt selPat)+)?
    ("with" (colGe inductionAlt)*)? : tactic

/--
  The `iinduction` tactic applies induction in the Iris Proof Mode in a similar
  way as the `induction` tactic. Given an expression `e`, the application of
  `iinduction e` performs the following steps:
  1. Generalises the expression `e` using `Lean.Meta.Tactic.Generalize`.
  2. Reverts all hypotheses in the spatial context, as well as those in the
     intuitionistic context that involves the variable to which induction is applied.
  3. Applies the built-in `induction` tactic in Lean to obtain the induction
     subgoals.
  4. Moves all induction hypotheses into the intuitionstic context.
  5. Introduce hypotheses reverted in steps 2 and 3 back into the Iris contexts.

  Similar to the regular `induction` tactic, the following syntax is available.
  - `iinduction e using r`: to specify the induction principle `r`.
  - `iinduction e generalizing z₁ ... zₙ`: to generalise `z₁ ... zₙ`,
    which is expressed as a selection pattern. Both Iris hypotheses and pure
    Lean hypotheses can be generalised.
  - `iinduction e with | constr₁ => tac₁ | ... | constrₙ => tacₙ`:
    the constructor names can either be long (e.g., `Nat.zero`) or short (e.g., `zero`).
    Arguments are optionally given names or otherwise remain inaccessible.

  As an example, consider the following Iris context, where `n : Nat`.

  ```
  ∗HP : P
  □HQ : Q
  □HR : R
  ∗HS : S
  □HT : T n
  ```

  By applying `iinduction n`, all spatial hypotheses (`HP` and `HS`) are
  reverted. The hypothesis `HT` is also reverted because it involves `n`.
  By applying `iinduction n generalizing HQ %R`, the hypotheses `HQ` and `HR`
  are additionally reverted and thus included as premises in the induction
  hypothesis.
-/
elab_rules : tactic
  | `(tactic| iinduction $x
        $[using $r]?
        $[generalizing $genSelPats*]?
        $[with $alts*]?) => do
    let fvar ← generalizeTermWithFVar x

    -- Parse the recursor name provided by the user
    let recName : Option Name := r.map (·.getId)

    -- Parse the list of alternative names supplied by the user
    let parsedAlts ← alts.mapM (·.mapM parseinductionAlt)

    ProofModeM.runTactic λ mvar { hyps, goal, .. } => do
      -- Parse the user-supplied list of variables to be generalised
      let genSelTargets ← genSelPats.mapM <| fun pats => do
        let parsed ← liftMacroM <| SelPat.parse pats
        SelPat.resolve hyps parsed

      let pf ← iInductionCore hyps goal fvar parsedAlts recName genSelTargets
      mvar.assign pf
