/-
Copyright (c) 2026 Yunsong Yang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yunsong Yang, Alvin Tang
-/
module

public meta import Iris.ProofMode.Tactics.Basic
public meta import Iris.ProofMode.Tactics.Assumption
public meta import Iris.ProofMode.Tactics.Cases
public meta import Iris.ProofMode.Patterns.CasesPattern
public meta import Iris.ProofMode.ClassesMake
public meta import Iris.ProofMode.Tactics.RevertIntro

namespace Iris.ProofMode

public meta section
open BI Std Lean Elab Tactic Meta Qq

/--
  The user of the `iinduction` tactic provides the proof for the induction
  subgoal. Induction hypotheses are available for the user in the intuitionistic
  context of the Iris proof state.

  Meanwhile, the actual induction subgoal generated by Lean with the `induction`
  tactic has induction hypotheses in the regular context.

  Given all hypotheses in the Iris proof state (represented by `P`) exist in
  the intuitionistic context (that is, the spatial context is empty), we can
  introduce another induction hypothesis generated by Lean into the
  intuitionistic context.
-/
@[rocq_alias tac_revert_ih]
theorem revert_IH [BI PROP] {P Q : PROP} {φ}
    (ih : φ)
    (h : R ⊢ □ P)
    (inst : IntoIH φ P Q) :
    R ⊢ □ (P ∗ □ Q) := calc
  _ ⊢ □ P         := h
  _ ⊢ □ P ∗ □ P   := intuitionistically_sep_dup.mp
  _ ⊢ □ P ∗ □ □ P := sep_mono_r intuitionistically_idem.mpr
  _ ⊢ □ P ∗ □ Q   := sep_mono_r <| intuitionistically_mono <| inst.into_ih ih
  _ ⊢ □ P ∗ □ □ Q := sep_mono_r intuitionistically_idem.mpr
  _ ⊢ □ (P ∗ □ Q) := intuitionistically_sep_2

/--
  Designed to be a mutable state such that `newHyps` contains induction
  hypotheses generated by Lean's built-in induction.
-/
private structure InductionState {u} {prop : Q(Type u)} {bi} (origE : Q($prop)) where
  {newE : Q($prop)}
  (newHyps : Hyps bi newE)
  (pf : Q($origE ⊢ □ $newE))

/--
  Given a collection of hypotheses (`hyps`) and a free variable `fvar`, return
  the subset of intuitionistic hypotheses in `hyps` that contains the `fvar`
  and all spatial hypotheses in the proof state.

  This function is used for identifying the hypotheses in the Iris proof state
  that must be reverted before applying Lean's built-in `induction` tactic.
-/
private def iHypsContaining {u} {prop : Q(Type $u)} {bi} {e : Q($prop)}
    (hyps : Hyps bi e) (fvar : FVarId) : List SelTarget :=
  let ivars := hyps.intuitionisticIVarIds.filter <| fun ivar =>
    match hyps.getDecl? ivar with
    | some (_, _, _, ty) => ty.containsFVar fvar
    | none => false

  (ivars ++ hyps.spatialIVarIds).map ({ kind := .ipm ·, explicit := false })

/--
  Search for hypotheses in the regular Lean context that represent induction
  hypotheses and return their IDs as a list.
-/
private def findIHs (m : MVarId) : MetaM (List FVarId) :=
  m.withContext do
    let lctx ← getLCtx
    let mut ihs := []
    for decl in lctx do
      let type ← instantiateMVars decl.type
      if isIrisGoal type then
        ihs := decl.fvarId :: ihs
    return ihs.reverse

/--
  Used for every induction hypothesis generated by Lean upon using the built-in
  `induction` tactic. The type class `IntoIH` is used for obtaining the
  corresponding proposition in the Iris proof mode.
-/
private def addIntoIH {u} {prop : Q(Type u)} {bi : Q(BI $prop)} {e}
    (st : @InductionState u prop bi e)
    (φ : Q(Prop)) (p : Q($φ)) (hFVar : FVarId) :
    ProofModeM (@InductionState u prop bi e) := do
  let oldE := st.newE
  let oldHyps : Hyps bi oldE := st.newHyps

  let Q ← mkFreshExprMVarQ q($prop)
  let some inst ← ProofModeM.trySynthInstanceQ q(IntoIH $φ $oldE $Q)
  | throwError "iinduction: type class synthesis with IntoIH failed"

  -- Introduce the induction hypothesis into the intuitionistic context
  let nameIdent := mkIdent <| ← hFVar.getUserName
  let binderIdent ← `(binderIdent| $nameIdent:ident)
  let ⟨_, newHyps⟩ ← Hyps.addWithInfo bi binderIdent q(true) Q oldHyps

  return { newHyps, pf := q(revert_IH $p $st.pf $inst) }

/--
  Introduce a list of induction hypotheses into Iris proof state.
  The list of `FVarId` values (`ihFVars`) should be the list returned by
  `findIHs`.
-/
private def addAllIHs {u} {prop : Q(Type u)} {bi : Q(BI $prop)} {e : Q($prop)}
    (pfIntHyps : Q($e ⊢ □ $e)) (hyps : Hyps bi e) (ihFVars : List FVarId) :
    ProofModeM (@InductionState u prop bi e) := do

  -- Initialise the mutable instance of `InductionState`
  let mut st : InductionState e := {
    newHyps := hyps, pf := q($pfIntHyps)
  }

  -- Iteratively move the induction hypotheses into the intuitionistic context
  for i in ihFVars do
    let p := mkFVar i
    let φ ← inferType (mkFVar i)
    st ← addIntoIH st φ p i

  return st

/--
  Given hypothesis `hyps` representing `e` where every hypothesis exist in the
  intuitionistic context, `e ⊢ □ e` must hold.
-/
private def buildPfIntHyps {u} {prop : Q(Type u)} {bi : Q(BI $prop)} {e}
    (hyps : Hyps bi e) : ProofModeM Q($e ⊢ □ $e) :=
  match hyps with
  | .emp _ =>
    pure q(intuitionistically_emp.mpr)
  | .hyp _ _ _ p _ _ =>
    match matchBool p with
    | .inl _ =>
      pure q(intuitionistically_idem.mpr)
    | .inr _ =>
      throwError "iinduction: spatial context is not empty after reverting hypotheses"
  | .sep _ _ _ _ lhs rhs => do
    let pfL ← buildPfIntHyps lhs
    let pfR ← buildPfIntHyps rhs
    pure q((sep_mono $pfL $pfR).trans intuitionistically_sep_2)

-- One case upon applying the `iinduction` tactic
syntax iinductionAlt := "| " ident ident* " => " tacticSeq

private def parseIInductionAlt (alt : TSyntax `Iris.ProofMode.iinductionAlt) :
    TacticM (Name × Array (TSyntax `ident) × TSyntax `Lean.Parser.Tactic.tacticSeq) := do
  let `(iinductionAlt| | $ctor:ident $vars:ident* => $tac:tacticSeq) := alt
  | throwError "iinduction: invalid syntax"

  return (ctor.getId, vars, tac)

/-- Check whether a fully-qualified constructor name (e.g. `Nat.succ`) matches a
    user-written short name (e.g. `succ`) or an already-qualified name. -/
private def matchesCtorName (fullName : Name) (userShort : Name) : Bool :=
  fullName == userShort || fullName.getString! == userShort.getString!

private def throwMissingAlt {α} (ctor : Name) : ProofModeM α :=
  throwError "iinduction: alternative `{ctor.getString!}` has not been provided"

private def checkCtors (ctors altCtors : List Name) : MetaM Unit := do
  let invalidAltCtors :=
    altCtors.filter fun alt =>
      not <| ctors.any fun ctor => matchesCtorName ctor alt

  if !invalidAltCtors.isEmpty then
    let invalids := String.intercalate ", " <| invalidAltCtors.map (s!"`{·}`")
    throwError m!"iinduction: invalid alternative names {invalids}"

private def iInductionCore {u} {prop : Q(Type u)} {bi : Q(BI $prop)} {e}
    (hyps : Hyps bi e) (goal : Q($prop)) (fvar : FVarId)
    (parsedAlts : Option <| Array <| Name × Array (TSyntax `ident) × TSyntax `Lean.Parser.Tactic.tacticSeq) :
    ProofModeM Q($e ⊢ $goal) := do
  -- Find all hypotheses that contain the variable being performed induction on
  let targets := iHypsContaining hyps fvar

  -- Find the recursor name for induction
  let fvarType ← whnf <| ← inferType <| mkFVar fvar
  let ⟨recName, ctors⟩ ← match fvarType.getAppFn with
  | .const indName _ =>
    match (← getEnv).find? indName with
    | some (.inductInfo val) => pure <| (Name.mkStr val.name "recOn", val.ctors)
    | _ => throwError "iinduction: {indName} is not inductive"
  | _ => throwError "iinduction: unable to determine inductive type"

  -- Define the names for variables and induction hypotheses if supplied by user
  let varNames : Array AltVarNames ←
    match parsedAlts with
    | none =>
      pure <| ctors.toArray.map (fun _ => {explicit := true, varNames := []})
    | some parsedAlts => do
      ctors.toArray.mapM fun ctor =>
      match parsedAlts.find? (fun (altCtor, _, _) => matchesCtorName ctor altCtor) with
      | some (_, vars, _) =>
        pure ({ explicit := true, varNames := vars.toList.map (·.getId) } : AltVarNames)
      | none => throwMissingAlt ctor

  -- Revert all hypotheses in the list
  let pf ← iRevertIntro hyps goal targets (
    -- The function takes the hypotheses and goal after reverting
    fun hyps' goal' k => do
      -- Create a new metavariable for the proof goal upon reverting hypotheses
      let m ← mkBIGoal hyps' goal'

      -- Use built-in induction in Lean to generate the subgoals for induction
      let subgoals ←  m.mvarId!.withContext do
        m.mvarId!.induction fvar recName varNames

      match parsedAlts with
      | none => pure ()
      | some parsedAlts => checkCtors ctors <| parsedAlts.toList.map Prod.fst

      -- Handle each subgoal generated by Lean's induction
      for (s, ctor) in subgoals.toList.zip ctors do
        s.mvarId.withContext do
          match parsedAlts with
          | none => pure ()
          | some parsedAlts =>
            match parsedAlts.find? (fun (altCtor, _, _) => matchesCtorName ctor altCtor) with
            | some (_, vars, _) =>
              for (fieldFVar, varStx) in s.fields.toList.zip vars.toList do
              let lctx ← getLCtx
              let fieldType ← inferType fieldFVar
              addLocalVarInfo varStx lctx fieldFVar (some fieldType) (isBinder := true)
            | none => throwMissingAlt ctor

          let sType ← instantiateMVars (← s.mvarId.getType)

          let some irisGoal := parseIrisGoal? sType
          -- This should not happen
          | throwError "iinduction: fail to parse induction subgoal"

          -- Find the induction hypotheses generated by Lean's `induction` tactic
          let ihFVars ← findIHs s.mvarId

          -- A proof that all hypotheses in the Iris goal exist in the intuitionistic context
          let pfIntHyps ← buildPfIntHyps irisGoal.hyps

          -- Introduce the induction hypothesis back into the Iris proof state
          let st ← addAllIHs pfIntHyps irisGoal.hyps ihFVars

          -- Remove the induction hypotheses from the regular Lean context
          let pf' ← withoutFVars (u := 0) ihFVars.toArray <| k st.newHyps irisGoal.goal

          s.mvarId.assign <| q($(st.pf).trans <| intuitionistically_elim.trans $pf')

          -- Case applicable for `with` syntax only
          match parsedAlts with
          | none => pure ()
          | some parsedAlts =>
            let biGoalMVar := (← getThe ProofModeM.State).goals.back!
            modify (fun s => { s with goals := s.goals.pop })

            let some (_, _, userTac) :=
            parsedAlts.find? (fun (altCtor, _, _) => matchesCtorName ctor altCtor)
            | throwMissingAlt ctor

            -- Run the user tactic on the BI goal
            let savedGoals ← getGoals
            setGoals [biGoalMVar]
            evalTactic userTac
            let remaining ← getGoals
            setGoals savedGoals
            for r in remaining do addMVarGoal r

      return m
  )

  return pf

/--
  Simple tactic with inaccessible names of variables and induction hypotheses
  generated by Lean automatically.
-/
elab "iinduction" colGt x:ident : tactic => do
  -- Get the ID of the variable on which induction is being performed
  let fvar ← getFVarId x

  ProofModeM.runTactic λ mvar { hyps, goal, .. } => do
    let pf ← iInductionCore hyps goal fvar none
    mvar.assign pf

/--
  Tactic with names of variables and induction hypotheses supplied by the user.
-/
elab "iinduction" colGt x:ident "with" alts:(colGe iinductionAlt)* : tactic => do
  -- Get the ID of the variable on which induction is being performed
  let fvar ← getFVarId x

  -- Parse the list of alternative names supplied by the user
  let parsedAlts ← alts.mapM parseIInductionAlt

  ProofModeM.runTactic λ mvar { hyps, goal, .. } => do
    let pf ← iInductionCore hyps goal fvar (some parsedAlts)
    mvar.assign pf
