/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zongyuan Liu
-/
import Iris.Std.RocqPorting

#rocq_ignore_file proofmode "base.v" "Rocq-specific basic functionality"
#rocq_ignore_file proofmode "coq_tactics.v" "Tracked via the Tactics concept"
#rocq_ignore_file proofmode "environments.v" "Implemented as Hyps in Expr.lean"
#rocq_ignore_file proofmode "ident_name.v" "Rocq-specific ident name handling"
#rocq_ignore_file proofmode "string_ident.v" "Rocq-specific string-based ident handling"
#rocq_ignore_file proofmode "tokens.v" "Rocq-specific tokenizer"

#rocq_concept proofmode "Tactics" missing "tactics"
#rocq_concept proofmode "Tactics" "iSolveSideCondition" ported "iSolveSideconditionAt"
#rocq_concept proofmode "Tactics" "iStartProof (basic)" ported "istart"
#rocq_concept proofmode "Tactics" "iStartProof (with bi specified)" missing ""
#rocq_concept proofmode "Tactics" "iStopProof" ported "istop"
#rocq_concept proofmode "Tactics" "iRename" ported "irename"
#rocq_concept proofmode "Tactics" "iClear" ported "iclear"
#rocq_concept proofmode "Tactics" "iEval" missing ""
#rocq_concept proofmode "Tactics" "iSimpl" missing ""
#rocq_concept proofmode "Tactics" "iUnfold" missing ""
#rocq_concept proofmode "Tactics" "iExact" ported "iexact"
#rocq_concept proofmode "Tactics" "iAssumption" ported "iassumption"
#rocq_concept proofmode "Tactics" "iAssumptionCoq" ignored "weird tactic"
#rocq_concept proofmode "Tactics" "iExFalso" ported "iexfalso"
#rocq_concept proofmode "Tactics" "iPure (basic)" ported "ipure"
#rocq_concept proofmode "Tactics" "iPure (pure destructuring patterns)" missing "(also for other tactics using ipure)"
#rocq_concept proofmode "Tactics" "iEmpIntro" ported "iemp_intro"
#rocq_concept proofmode "Tactics" "iPureIntro" ported "ipure_intro"
#rocq_concept proofmode "Tactics" "iFrame (basic)" ported "iframe"
#rocq_concept proofmode "Tactics" "iFrame (existential quantifiers)" missing ""
#rocq_concept proofmode "Tactics" "iRevert" ported "irevert"
#rocq_concept proofmode "Tactics" "iPoseProof" ported "ihave _ := _"
#rocq_concept proofmode "Tactics" "iSpecialize (basic)" ported "ispecialize"
#rocq_concept proofmode "Tactics" "iSpecialize (duplicate context for persistent conclusion)" ported "ispecialize"
#rocq_concept proofmode "Tactics" "iSpecialize (all specialization patterns)" missing ""
#rocq_concept proofmode "Tactics" "iApply" ported "iapply"
#rocq_concept proofmode "Tactics" "iLeft" ported "ileft"
#rocq_concept proofmode "Tactics" "iRight" ported "iright"
#rocq_concept proofmode "Tactics" "iSplit" ported "isplit"
#rocq_concept proofmode "Tactics" "iExists" ported "iexists"
#rocq_concept proofmode "Tactics" "iModIntro" ported "imodintro"
#rocq_concept proofmode "Tactics" "iNext (basic)" ported "inext"
#rocq_concept proofmode "Tactics" "iNext (with later credits)" missing ""
#rocq_concept proofmode "Tactics" "iMod" ported "imod"
#rocq_concept proofmode "Tactics" "iDestruct (basic)" ported "icases"
#rocq_concept proofmode "Tactics" "iDestruct (all destruct patterns)" missing ""
#rocq_concept proofmode "Tactics" "iCombine" missing ""
#rocq_concept proofmode "Tactics" "iIntros (basic)" ported "iintro"
#rocq_concept proofmode "Tactics" "iIntros (all intro patterns)" missing ""
#rocq_concept proofmode "Tactics" "iInduction" missing ""
#rocq_concept proofmode "Tactics" "iLöb" ported "iloeb"
#rocq_concept proofmode "Tactics" "iAssert" ported "ihave _ : _"
#rocq_concept proofmode "Tactics" "iRewrite" ported "irewrite"
#rocq_concept proofmode "Tactics" "iInv" missing ""
#rocq_concept proofmode "Tactics" "iAccu" missing ""
#rocq_concept proofmode "Tactics" "rules for trivial" ported "itrivial"

#rocq_concept proofmode "Intro Patterns" missing ""
#rocq_concept proofmode "Intro Patterns" "IIdent (pattern: H)" ported "pattern: H"
#rocq_concept proofmode "Intro Patterns" "IFresh (pattern: ?)" ported "pattern: _"
#rocq_concept proofmode "Intro Patterns" "IDrop (pattern: _)" ported "pattern: -"
#rocq_concept proofmode "Intro Patterns" "IFrame (pattern: $)" ported "pattern: $"
#rocq_concept proofmode "Intro Patterns" "IList (pattern: [ ... ])" ported "pattern: ⟨ ... ⟩"
#rocq_concept proofmode "Intro Patterns" "IList (pattern: [ ... | ... ])" ported "pattern: ( ... | ... )"
#rocq_concept proofmode "Intro Patterns" "IPure (pattern: %x)" ported "pattern: %x"
#rocq_concept proofmode "Intro Patterns" "IIntuitionistic (pattern: #H)" ported "pattern: #H"
#rocq_concept proofmode "Intro Patterns" "ISpatial (pattern: -#H)" ported "pattern: ∗H"
#rocq_concept proofmode "Intro Patterns" "IModalElim (pattern: >H)" ported "pattern: >H"
#rocq_concept proofmode "Intro Patterns" "IRewrite (pattern: ->/<-)" missing ""
#rocq_concept proofmode "Intro Patterns" "IPureIntro (pattern: !%)" missing ""
#rocq_concept proofmode "Intro Patterns" "IModalIntro (pattern: !>)" ported "pattern: !>"
#rocq_concept proofmode "Intro Patterns" "ISimpl (pattern: /=)" missing ""
#rocq_concept proofmode "Intro Patterns" "IDone (pattern: //)" ported "pattern: //"
#rocq_concept proofmode "Intro Patterns" "IForall (pattern: *)" missing ""
#rocq_concept proofmode "Intro Patterns" "IAll (pattern: **)" missing ""
#rocq_concept proofmode "Intro Patterns" "IClear (pattern: {selpat})" missing ""
#rocq_concept proofmode "Intro Patterns" "IClearFrame (pattern: {$selpat})" missing ""

#rocq_concept proofmode "Specialization Patterns" missing ""
#rocq_concept proofmode "Specialization Patterns" "SIdent (pattern: H)" ported "pattern: H"
#rocq_concept proofmode "Specialization Patterns" "Nested (pattern: (H spat ...))" missing ""
#rocq_concept proofmode "Specialization Patterns" "SPureGoal (pattern: [%])" ported "pattern: %"
#rocq_concept proofmode "Specialization Patterns" "SGoal (Kind: Spatial) (pattern: [H1 ...])" ported "pattern: [H1 ...]"
#rocq_concept proofmode "Specialization Patterns" "SGoal (Kind: Intuitionistic) (pattern: [#H1 ...])" missing "pattern: [#H1 ...]"
#rocq_concept proofmode "Specialization Patterns" "SGoal (Kind: Modal) (pattern: [>H1 ...])" missing "pattern: [>H1 ...]"
#rocq_concept proofmode "Specialization Patterns" "SGoal (Negate) (pattern: [-H1 ...])" ported "pattern: [-H1 ...]"
#rocq_concept proofmode "Specialization Patterns" "SGoal (Frame) (pattern: [$H1])" ported "pattern: [$H1]"
#rocq_concept proofmode "Specialization Patterns" "SGoal (Hyps) (pattern: [H1 ...])" ported "pattern: [H1 ...]"
#rocq_concept proofmode "Specialization Patterns" "SGoal (Done) (pattern: [... //])" ported "pattern: [... //]"
#rocq_concept proofmode "Specialization Patterns" "SAutoFrame (Kind: Spatial) (pattern: [$])" ported "pattern: [$]"
#rocq_concept proofmode "Specialization Patterns" "SAutoFrame (Kind: Intuitionistic) (pattern: [#$])" missing "pattern: [#$]"
#rocq_concept proofmode "Specialization Patterns" "SAutoFrame (Kind: Modal) (pattern: [>$])" missing "pattern: [>$]"
