/-
Adapted from Mathlib.Tactic.Linter.Lint
Copyright (c) 2023 Floris van Doorn. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Floris van Doorn
-/
module

public import Batteries.Tactic.Lint
public import Lean.Linter.Deprecated
public meta import Lean.Linter.Basic
public meta import Iris.Std.Linter.DeclarationNames

meta section

namespace Iris.Std.Linter

/-!
### `dupNamespace` linter

The `dupNamespace` linter produces a warning when a component of a declaration name is repeated
several times. The repetition does not have to be consecutive. Examples: `Nat.Nat.foo`,
`One.two.two`, `Nat.One.Nat`, `Nat.Prime.Nat.Prime.foo`, `Nat.Prime.Nat.bar`

The linter also warns about auto-generated declarations (such as, those generated by `to_additive`).
-/

/--
The `dupNamespace` linter produces a warning when a component of a declaration name is repeated
several times. The repetition does not have to be consecutive. Examples: `Nat.Nat.foo`,
`One.two.two`, `Nat.One.Nat`, `Nat.Prime.Nat.Prime.foo`, `Nat.Prime.Nat.bar`

The linter also warns about auto-generated declarations (such as, those generated by `to_additive`).
-/
public register_option linter.iris.dupNamespace : Bool := {
  defValue := true
  descr := "enable the duplicated namespace linter"
}

namespace DupNamespaceLinter

open Lean Parser Elab Command Meta Iris Std Linter

@[inherit_doc linter.iris.dupNamespace]
def dupNamespace : Linter where run := withSetOptionIn fun stx ↦ do
  if getLinterValue linter.iris.dupNamespace (← getLinterOptions) then
    let mut aliases := #[]
    if let some exp := stx.find? (·.isOfKind `Lean.Parser.Command.export) then
      aliases ← getAliasSyntax exp
    for id in (← getNamesFrom (stx.getPos?.getD default)) ++ aliases do
      let declName := id.getId
      -- We intentionally *do* lint deprecated declarations:
      -- this is important since people can forget to add a `_root_` when adding deprecations.
      if declName.hasMacroScopes || isPrivateName declName then continue
      -- Specific to Iris-Lean: this linter should not apply to `rocq_alias` entries
      if declName.getRoot == `Rocq then continue
      let nm := declName.components
      -- Collect distinct components which appear more than once.
      let duplicated := List.eraseDups <| nm.filter (fun comp ↦ nm.count comp > 1)
      match duplicated with
      | [] => continue
      | [ns] =>
        Linter.logLint linter.iris.dupNamespace id
          m!"The namespace `{ns}` is duplicated in the declaration \
          `{.ofConstName (fullNames := true) declName}`."
      | dup =>
        let ns := MessageData.andList (duplicated.map (m!"`{·}`"))
        Linter.logLint linter.iris.dupNamespace id
          m!"The namespaces {ns} are duplicated in the declaration \
          `{.ofConstName (fullNames := true) declName}`."

initialize addLinter dupNamespace

end Iris.Std.Linter.DupNamespaceLinter
