name = "irismath"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["IrisMath", "IrisMathTest"]

[leanOptions]
pp.unicode.fun = true 
relaxedAutoImplicit = true
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
weak.linter.style.header = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[require]]
name = "iris"
path = "../Iris/"

[[lean_lib]]
name = "IrisMath"

[[lean_lib]]
name = "IrisMathTest"

[[lean_exe]]
name = "check-imports"
srcDir = "../scripts"
root = "CheckImports"
