/-
Copyright (c) 2026 Iris-Lean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.MeasureTheory.MeasurableSpace.Defs
public import Mathlib.Probability.Process.Filtration
public import Iris

@[expose] public section

/-!
# σ-algebras as an idempotent UCMRA

`MeasurableSpace Ω` carries a `CompleteLattice` structure in Mathlib: σ-algebras
on `Ω` are ordered by inclusion (`m₁ ≤ m₂` iff every `m₁`-measurable set is
`m₂`-measurable). We expose this lattice as an idempotent UCMRA
`SigmaAlgebraCMRA Ω` whose operation is supremum and whose unit is `⊥` (the
trivial σ-algebra `{∅, Ω}`).

The intuition for the operation: `m₁ + m₂` is the **smallest σ-algebra
containing both** `m₁` and `m₂`. Concretely, it is generated by the union of
the measurable sets of `m₁` and `m₂`, so it carries strictly more information
than either factor — every `m₁`-measurable set and every `m₂`-measurable set is
`m₁ + m₂`-measurable. Idempotence (`m + m = m`) reflects the fact that "joining
knowledge with itself" yields nothing new, which in turn makes every σ-algebra
its own CMRA core.

This is the σ-algebra analogue of `IrisMath.Lattice.SubmoduleCMRA` and
`IrisMath.Lattice.FilterCMRA`. As for those, the carrier is wrapped in
`LeibnizO` (discrete + Leibniz OFE) and the UCMRA structure comes from the
`OrdCommMonoidLike` recipe, surfaced by directly referencing the underlying
scoped instance names (`OrdCommMonoidLike.instCMRA` etc.).

The final section connects this CMRA to Mathlib's `MeasureTheory.Filtration`:
a filtration `f : Filtration ℕ m` yields a sequence
`filtrationSeq f n : SigmaAlgebraCMRA Ω`, monotone in the σ-algebra lattice
order — which is exactly the CMRA inclusion direction witnessed by `op_ge_left`.
-/

open Iris OFE CMRA Std MeasureTheory

namespace IrisMath.SigmaAlgebra

/-- σ-algebras on `Ω` as a UCMRA under supremum (`⊔`), with unit `⊥`. The
operation `m₁ + m₂` is the smallest σ-algebra containing both `m₁` and `m₂`,
and every σ-algebra is its own core. -/
def SigmaAlgebraCMRA (Ω : Type _) : Type _ := LeibnizO (MeasurableSpace Ω)

namespace SigmaAlgebraCMRA

variable {Ω : Type _}

instance : COFE (SigmaAlgebraCMRA Ω) := inferInstanceAs (COFE (LeibnizO _))
instance : OFE.Discrete (SigmaAlgebraCMRA Ω) := inferInstanceAs (OFE.Discrete (LeibnizO _))
instance : OFE.Leibniz (SigmaAlgebraCMRA Ω) := inferInstanceAs (OFE.Leibniz (LeibnizO _))

/-- The CMRA operation: σ-algebra supremum, i.e. the smallest σ-algebra
containing both arguments. -/
instance : Add (SigmaAlgebraCMRA Ω) := ⟨fun a b ↦ ⟨a.car ⊔ b.car⟩⟩

/-- The CMRA unit: the trivial σ-algebra `⊥`. -/
instance : Zero (SigmaAlgebraCMRA Ω) := ⟨⟨⊥⟩⟩

/-- Unfolding lemma for the operation. -/
theorem add_def (a b : SigmaAlgebraCMRA Ω) : a + b = ⟨a.car ⊔ b.car⟩ := rfl

/-- Unfolding lemma for the unit. -/
theorem zero_def : (0 : SigmaAlgebraCMRA Ω) = ⟨⊥⟩ := rfl

instance : Std.Associative (Add.add (α := SigmaAlgebraCMRA Ω)) where
  assoc a b c :=
    show (⟨(a.car ⊔ b.car) ⊔ c.car⟩ : SigmaAlgebraCMRA Ω)
        = ⟨a.car ⊔ (b.car ⊔ c.car)⟩ by
      rw [sup_assoc]

instance : Std.Commutative (Add.add (α := SigmaAlgebraCMRA Ω)) where
  comm a b :=
    show (⟨a.car ⊔ b.car⟩ : SigmaAlgebraCMRA Ω) = ⟨b.car ⊔ a.car⟩ by
      rw [sup_comm]

instance : Std.IdempotentOp (Add.add (α := SigmaAlgebraCMRA Ω)) where
  idempotent a :=
    show (⟨a.car ⊔ a.car⟩ : SigmaAlgebraCMRA Ω) = a by
      cases a
      simp

instance :
    Std.LawfulLeftIdentity (Add.add (α := SigmaAlgebraCMRA Ω)) (0 : SigmaAlgebraCMRA Ω) where
  left_id a :=
    show (⟨(⊥ : MeasurableSpace Ω) ⊔ a.car⟩ : SigmaAlgebraCMRA Ω) = a by
      cases a
      simp

instance : CMRA (SigmaAlgebraCMRA Ω) := OrdCommMonoidLike.instCMRA
instance : CMRA.Discrete (SigmaAlgebraCMRA Ω) := OrdCommMonoidLike.instDiscrete
instance : UCMRA (SigmaAlgebraCMRA Ω) := OrdCommMonoidLike.instUCMRAOfLawfulLeftIdentityAddZero

/-- Every σ-algebra is its own core. -/
example (a : SigmaAlgebraCMRA Ω) : CMRA.CoreId a := OrdCommMonoidLike.instCoreId _

/-- Sup of σ-algebras is idempotent: every σ-algebra is its own operation. This
is the elementary witness that the CMRA is idempotent, before any wrapping
through `CoreId`. -/
theorem op_self (a : SigmaAlgebraCMRA Ω) : a + a = a :=
  Std.IdempotentOp.idempotent (op := Add.add (α := SigmaAlgebraCMRA Ω)) a

/-- The CMRA operation dominates each argument in the σ-algebra lattice: the
combined σ-algebra refines `a`, i.e. every `a`-measurable set is
`a + b`-measurable. -/
theorem op_ge_left (a b : SigmaAlgebraCMRA Ω) : a.car ≤ (a + b).car := le_sup_left

/-- Symmetric companion to `op_ge_left`. -/
theorem op_ge_right (a b : SigmaAlgebraCMRA Ω) : b.car ≤ (a + b).car := le_sup_right

/-- Sanity example: two σ-algebras combine via `+` to their supremum. -/
example (m₁ m₂ : MeasurableSpace Ω) :
    let a : SigmaAlgebraCMRA Ω := ⟨m₁⟩
    let b : SigmaAlgebraCMRA Ω := ⟨m₂⟩
    a + b = ⟨m₁ ⊔ m₂⟩ := rfl

/-- Sanity example: combining the trivial σ-algebra `⊥` with the discrete
σ-algebra `⊤` recovers `⊤`, i.e. `⊥` is absorbed by any larger σ-algebra (it is
the unit of the operation). -/
example :
    let a : SigmaAlgebraCMRA Ω := ⟨⊥⟩
    let b : SigmaAlgebraCMRA Ω := ⟨⊤⟩
    a + b = ⟨⊤⟩ := by
  change (⟨(⊥ : MeasurableSpace Ω) ⊔ ⊤⟩ : SigmaAlgebraCMRA Ω) = ⟨⊤⟩
  rw [bot_sup_eq]

/-! ## Filtrations as sequences of `SigmaAlgebraCMRA`

A `MeasureTheory.Filtration ℕ m` is, by definition, a monotone sequence of
sub-σ-algebras of `m`. Packaging each level as a `SigmaAlgebraCMRA` exposes the
filtration as a sequence of CMRA elements, with monotonicity in the underlying
σ-algebra lattice — which is exactly the inclusion direction witnessed by
`op_ge_left`/`op_ge_right`. -/

/-- The CMRA-valued sequence associated to a filtration: at time `n`, return
the σ-algebra `f.seq n` wrapped as a `SigmaAlgebraCMRA Ω`. -/
def filtrationSeq {m : MeasurableSpace Ω} (f : Filtration ℕ m) (n : ℕ) :
    SigmaAlgebraCMRA Ω :=
  ⟨f.seq n⟩

@[simp] theorem filtrationSeq_car {m : MeasurableSpace Ω} (f : Filtration ℕ m) (n : ℕ) :
    (filtrationSeq f n).car = f.seq n := rfl

/-- A filtration produces a monotone sequence in the σ-algebra lattice
underlying `SigmaAlgebraCMRA`. Combined with `op_ge_left`, this says that every
`f.seq j`-measurable set remains measurable at any later time `k`. -/
theorem filtrationSeq_mono {m : MeasurableSpace Ω} (f : Filtration ℕ m) {j k : ℕ}
    (h : j ≤ k) : (filtrationSeq f j).car ≤ (filtrationSeq f k).car :=
  f.mono h

end SigmaAlgebraCMRA

end IrisMath.SigmaAlgebra
