/-
Copyright (c) 2026 Iris-Lean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Topology.Order
public import Iris

@[expose] public section

/-!
# The lattice of topologies on a fixed set as a CMRA of fineness

This file exposes `TopologicalSpaceCMRA X`: the type of topologies on a fixed
set `X`, equipped with an idempotent UCMRA structure whose operation is
supremum (join in the lattice of topologies) and whose unit is `⊥`, the
indiscrete topology. Combining two topologies via `+` yields the **coarsest
topology finer than both** — the smallest topology containing every open of
each argument.

## Orientation of the order

`TopologicalSpace X` carries a `CompleteLattice` structure in
`Mathlib.Topology.Order`, but the order is **reversed** from the naive
expectation: `t₁ ≤ t₂` means `t₁` is *coarser* than `t₂`, i.e. `t₁` has
*fewer* opens. Consequently:

* `⊥` is the indiscrete topology `{∅, X}` (the coarsest topology, fewest opens).
* `⊤` is the discrete topology (the finest topology, every set open).
* `t₁ ⊔ t₂` is "finer than both", generated by the union of the two open-set
  collections.
* `t₁ ⊓ t₂` is the intersection of the open-set collections (coarser than
  both).

Under this convention, the CMRA operation `t₁ + t₂ := t₁ ⊔ t₂` accumulates
opens, mirroring the σ-algebra construction in `IrisMath.SigmaAlgebra` and the
open-set construction in `IrisMath.Opens`. Idempotence (`t + t = t`) reflects
that joining a topology with itself yields nothing new, which in turn makes
every topology its own CMRA core.

## Side note: `Bornology X`

The design note originally targeted `Bornology X` for an analogous
construction, but Mathlib does not equip `Bornology X` with a `CompleteLattice`
(or even `SemilatticeSup`) instance — bornologies are determined by their
cobounded filters, yet the pointwise lattice operations are not exposed on the
type. `TopologicalSpace X` is the closest viable target and is the carrier
used here.

## Implementation

The carrier is wrapped in `LeibnizO` (discrete + Leibniz OFE) and the UCMRA
structure comes from the `OrdCommMonoidLike` recipe, surfaced by directly
referencing the underlying scoped instance names (`OrdCommMonoidLike.instCMRA`
etc.). This is the topological analogue of `IrisMath.Lattice.SubmoduleCMRA`,
`IrisMath.SigmaAlgebra.SigmaAlgebraCMRA`, and the open-set construction in
`IrisMath.Opens`.
-/

open Iris OFE CMRA Std

namespace IrisMath.TopologicalSpace

/-- Topologies on `X` as a UCMRA under supremum (`⊔`), with unit `⊥` (the
indiscrete topology). The operation `t₁ + t₂` is the smallest topology
containing both `t₁` and `t₂`, and every topology is its own core. -/
def TopologicalSpaceCMRA (X : Type _) : Type _ := LeibnizO (TopologicalSpace X)

namespace TopologicalSpaceCMRA

variable {X : Type _}

instance : COFE (TopologicalSpaceCMRA X) := inferInstanceAs (COFE (LeibnizO _))
instance : OFE.Discrete (TopologicalSpaceCMRA X) :=
  inferInstanceAs (OFE.Discrete (LeibnizO _))
instance : OFE.Leibniz (TopologicalSpaceCMRA X) :=
  inferInstanceAs (OFE.Leibniz (LeibnizO _))

/-- The CMRA operation: supremum of topologies, i.e. the smallest topology
finer than both arguments. -/
instance : Add (TopologicalSpaceCMRA X) := ⟨fun a b ↦ ⟨a.car ⊔ b.car⟩⟩

/-- The CMRA unit: the indiscrete topology `⊥`. -/
instance : Zero (TopologicalSpaceCMRA X) := ⟨⟨⊥⟩⟩

/-- Unfolding lemma for the operation. -/
theorem add_def (a b : TopologicalSpaceCMRA X) : a + b = ⟨a.car ⊔ b.car⟩ := rfl

/-- Unfolding lemma for the unit. -/
theorem zero_def : (0 : TopologicalSpaceCMRA X) = ⟨⊥⟩ := rfl

instance : Std.Associative (Add.add (α := TopologicalSpaceCMRA X)) where
  assoc a b c :=
    show (⟨(a.car ⊔ b.car) ⊔ c.car⟩ : TopologicalSpaceCMRA X)
        = ⟨a.car ⊔ (b.car ⊔ c.car)⟩ by
      rw [sup_assoc]

instance : Std.Commutative (Add.add (α := TopologicalSpaceCMRA X)) where
  comm a b :=
    show (⟨a.car ⊔ b.car⟩ : TopologicalSpaceCMRA X) = ⟨b.car ⊔ a.car⟩ by
      rw [sup_comm]

instance : Std.IdempotentOp (Add.add (α := TopologicalSpaceCMRA X)) where
  idempotent a :=
    show (⟨a.car ⊔ a.car⟩ : TopologicalSpaceCMRA X) = a by
      cases a
      simp

instance :
    Std.LawfulLeftIdentity (Add.add (α := TopologicalSpaceCMRA X))
      (0 : TopologicalSpaceCMRA X) where
  left_id a :=
    show (⟨(⊥ : TopologicalSpace X) ⊔ a.car⟩ : TopologicalSpaceCMRA X) = a by
      cases a
      simp

instance : CMRA (TopologicalSpaceCMRA X) := OrdCommMonoidLike.instCMRA
instance : CMRA.Discrete (TopologicalSpaceCMRA X) := OrdCommMonoidLike.instDiscrete
instance : UCMRA (TopologicalSpaceCMRA X) :=
  OrdCommMonoidLike.instUCMRAOfLawfulLeftIdentityAddZero

/-- Every topology is its own core. -/
example (a : TopologicalSpaceCMRA X) : CMRA.CoreId a := OrdCommMonoidLike.instCoreId _

/-- Every topology is its own operation: `a + a = a`, because sup is
idempotent. -/
theorem op_self (a : TopologicalSpaceCMRA X) : a + a = a :=
  Std.IdempotentOp.idempotent (op := Add.add (α := TopologicalSpaceCMRA X)) a

/-- The CMRA operation dominates each argument in the lattice of topologies:
`a ≤ a + b`. Recall that `≤` on `TopologicalSpace X` is *coarser-than*, so this
says the combined topology is finer than `a`, i.e. every `a`-open set is also
`a + b`-open. -/
theorem le_op_left (a b : TopologicalSpaceCMRA X) : a.car ≤ (a + b).car := le_sup_left

/-- Symmetric companion to `le_op_left`: `b ≤ a + b`. -/
theorem le_op_right (a b : TopologicalSpaceCMRA X) : b.car ≤ (a + b).car := le_sup_right

/-- Sanity example: two topologies combine via `+` to their supremum. -/
example (t₁ t₂ : TopologicalSpace X) :
    (show TopologicalSpaceCMRA X from ⟨t₁⟩) + (show TopologicalSpaceCMRA X from ⟨t₂⟩)
      = (show TopologicalSpaceCMRA X from ⟨t₁ ⊔ t₂⟩) := rfl

/-- Sanity example: indiscrete `+` discrete `=` discrete. The indiscrete
topology `⊥` is absorbed by the discrete topology `⊤` (the unit law on the
right, viewed via the reversed order). -/
example :
    (show TopologicalSpaceCMRA X from ⟨⊥⟩) + (show TopologicalSpaceCMRA X from ⟨⊤⟩)
      = (show TopologicalSpaceCMRA X from ⟨⊤⟩) := by
  change (⟨(⊥ : TopologicalSpace X) ⊔ ⊤⟩ : TopologicalSpaceCMRA X) = ⟨⊤⟩
  rw [bot_sup_eq]

end TopologicalSpaceCMRA

end IrisMath.TopologicalSpace
