/- A description of the tactics can be found in `tactics.md`. -/
import Iris.ProofMode.Tactics.Apply
import Iris.ProofMode.Tactics.Assumption
import Iris.ProofMode.Tactics.Basic
import Iris.ProofMode.Tactics.Cases
import Iris.ProofMode.Tactics.Clear
import Iris.ProofMode.Tactics.Exact
import Iris.ProofMode.Tactics.ExFalso
import Iris.ProofMode.Tactics.Exists
import Iris.ProofMode.Tactics.Have
import Iris.ProofMode.Tactics.Intro
import Iris.ProofMode.Tactics.LeftRight
import Iris.ProofMode.Tactics.Move
import Iris.ProofMode.Tactics.Pure
import Iris.ProofMode.Tactics.Remove
import Iris.ProofMode.Tactics.Revert
import Iris.ProofMode.Tactics.Rename
import Iris.ProofMode.Tactics.Specialize
import Iris.ProofMode.Tactics.Split
